name: clean_architecture
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  easy_localization: ^3.0.7
  flash: ^3.1.1
  ansicolor: ^2.0.3
  dio: ^5.7.0
  gap: ^3.0.1
  go_router: ^14.2.8
  internet_connection_checker: ^1.0.0+1
  path_provider: ^2.1.5
  path: ^1.9.0
  hive: ^2.2.3
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  url_launcher: ^6.3.1
  mask_text_input_formatter: ^2.9.0
  flutter_multi_formatter: ^2.13.0
  carousel_slider: ^5.0.0
  keyboard_dismisser: ^3.0.0
  flutter_easyloading: ^3.0.5
  image_picker: ^1.1.2
  permission_handler: ^11.0.0
  app_links: ^6.4.0
  location: ^5.0.0
  camera: ^0.11.0
  qr_flutter: ^4.1.0
  share_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/locale/

  fonts:
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 100